# Generated by Django 3.2.7 on 2021-09-24 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, '技术类'), (1, '内容类'), (2, '营销类'), (3, '运营类'), (4, '设计类'), (5, '产品类')], verbose_name='职位类别')),
                ('job_title', models.CharField(max_length=250, verbose_name='职位名称')),
                ('job_city', models.SmallIntegerField(choices=[(0, '北京'), (1, '上海'), (2, '广州'), (3, '深圳'), (4, '杭州'), (5, '成都')], verbose_name='工作地点')),
                ('job_description', models.TextField(max_length=1024, verbose_name='工作职责')),
                ('job_requirement', models.TextField(max_length=1024, verbose_name='工作要求')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
