# Generated by Django 3.2.7 on 2021-09-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210924_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
