# Generated by Django 3.2.7 on 2021-09-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210926_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='apply_position',
            field=models.CharField(blank=True, max_length=128, verbose_name='应聘职位'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bachelor_school',
            field=models.CharField(blank=True, max_length=128, verbose_name='学士学校'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='born_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='生源地'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_remark',
            field=models.CharField(blank=True, max_length=128, verbose_name='候选人备注'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='creator',
            field=models.CharField(blank=True, max_length=128, verbose_name='候选人备注'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='degree',
            field=models.CharField(blank=True, choices=[('学士', '学士'), ('硕士', '硕士'), ('博士', '博士')], max_length=128, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='doctor_school',
            field=models.CharField(blank=True, max_length=128, verbose_name='博士学校'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_interviewer',
            field=models.CharField(blank=True, max_length=128, verbose_name='面试官'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_recommend_position',
            field=models.CharField(blank=True, max_length=128, verbose_name='推荐部门'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_remark',
            field=models.CharField(blank=True, max_length=128, verbose_name='初试备注'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, max_length=128, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hr_interviewer',
            field=models.CharField(blank=True, max_length=128, verbose_name='面试官'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hr_remark',
            field=models.CharField(blank=True, max_length=128, verbose_name='终试备注'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_editor',
            field=models.CharField(blank=True, max_length=128, verbose_name='最后编辑者'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='major',
            field=models.CharField(blank=True, max_length=128, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='master_school',
            field=models.CharField(blank=True, max_length=128, verbose_name='硕士学校'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_interviewer',
            field=models.CharField(blank=True, max_length=128, verbose_name='面试官'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_recommend_position',
            field=models.CharField(blank=True, max_length=128, verbose_name='推荐部门'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_remark',
            field=models.CharField(blank=True, max_length=128, verbose_name='复试备注'),
        ),
    ]
