# Generated by Django 3.2.7 on 2021-09-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20210926_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='creator',
            field=models.CharField(blank=True, max_length=128, verbose_name='创建人'),
        ),
    ]
