# Generated by Django 3.2.7 on 2021-09-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_candidate_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=128, verbose_name='性别'),
        ),
    ]
