# Generated by Django 3.2.7 on 2021-09-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_alter_candidate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='first_interviewer',
            field=models.CharField(blank=True, max_length=128, verbose_name='初试面试官'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hr_interviewer',
            field=models.CharField(blank=True, max_length=128, verbose_name='终试面试官'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_interviewer',
            field=models.CharField(blank=True, max_length=128, verbose_name='复试面试官'),
        ),
    ]
